language: node_js
node_js:
  - '8.4.0'
services:
  - mongodb
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
env:
  - CXX=g++-5
sudo: required
# safelist
branches:
  only:
  - master
  - staging
  - development

  # except:
  #   -
before_script: npm i
script:
  # - npm run lint
  - npm test
